name: CI

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'

    # We're running on ubuntu-latest, nothing special
    runs-on: ubuntu-latest
    steps:
      # As usual, we simply checkout the project
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm install

      # Now we're building the svelte site.
      # This step generates a build/ directory.
      - name: Build site
        run: npm run build

      # This seems to be the simplest way to publish to a separate branch.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
          # Optional. This will create a CNAME file so GitHub Pages serves it
          # under this domain.
          # cname:
